### **[실습] 기본 실습**

| Name | Age | City | Salary |
| --- | --- | --- | --- |
| Alice | 25 | New York | 70000 |
| Bob | 30 | Los Angeles | 80000 |
| Charlie | 35 | Chicago | 120000 |
| David | 40 | Houston | 90000 |
| Eve | 28 | San Francisco | 75000 |
- 다음 데이터를 활용하여 실습 문제를 해결하세요.
1. **DataFrame객체 생성 :** 위의 데이터를 사용해 DataFrame객체를 생성하세요.

In [4]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco'],
    'Salary': [70000, 80000, 120000, 90000, 75000]
})

df

      Name  Age           City  Salary
0    Alice   25       New York   70000
1      Bob   30    Los Angeles   80000
2  Charlie   35        Chicago  120000
3    David   40        Houston   90000
4      Eve   28  San Francisco   75000

2. **열과 행 선택**
    - `Name`과 `City` 열을 선택하여 출력하세요.
    - 나이가 30 이상인 행을 선택하여 출력하세요.

In [19]:
df[['Name', 'City']]
df[df['Age'] >= 30]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago  120000
3    David   40      Houston   90000

3. **행과 열 추가**
    - `Country` 열을 추가하고, 모두 'USA'로 설정하세요.
    - 새로운 행을 추가하세요. (Name: Frank, Age: 33, City: Seattle, Salary: 85000)

In [23]:
df['Contry'] = ['USA', 'USA', 'USA', 'USA', 'USA']
df
df.loc[5] = ['Frank', 33, 'Seattle', 85000, 'USA']
df

      Name  Age           City  Salary Contry
0    Alice   25       New York   70000    USA
1      Bob   30    Los Angeles   80000    USA
2  Charlie   35        Chicago  120000    USA
3    David   40        Houston   90000    USA
4      Eve   28  San Francisco   75000    USA
5    Frank   33        Seattle   85000    USA

4. **데이터 삭제**
    - `Salary` 열을 삭제하세요.
    - 'David'가 있는 행을 삭제하세요.

In [29]:
# df = df.drop('Salary', axis=1)
df = df.drop(3)

df

      Name  Age           City Contry
0    Alice   25       New York    USA
1      Bob   30    Los Angeles    USA
2  Charlie   35        Chicago    USA
4      Eve   28  San Francisco    USA
5    Frank   33        Seattle    USA

5. **데이터 수정**
    - `Age`가 35 이상인 사람들의 `Salary`를 5% 증가시키세요.
    - 'Alice'의 `City`를 'Boston'으로 수정하세요.

In [52]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco'],
    'Salary': [70000, 80000, 120000, 90000, 75000]
})

df_age35 = df[df['Age'] >= 35]
df.loc[df['Age'] >= 35, 'Salary'] = df['Salary'] * 1.05
df.loc[df['Name'] == 'Alice', 'City'] = 'Boston'

df

      Name  Age           City  Salary
0    Alice   25         Boston   70000
1      Bob   30    Los Angeles   80000
2  Charlie   35        Chicago  126000
3    David   40        Houston   94500
4      Eve   28  San Francisco   75000

6. **데이터 타입 변환**
    - `Age`와 `Salary`의 데이터 타입을 float로 변환하세요.

### **[실습 1] 데이터 정리 및 전처리**

다음은 직장 내 직원 데이터입니다. 결측된 값들이 포함되어 있습니다. `Salary`와 `YearsAtCompany`의 결측값을 각 열의 평균값으로 채우세요.

```python
employee_data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['John', 'Emily', 'Sara', 'Tom', 'Anna'],
    'Department': ['HR', 'IT', 'Marketing', None, 'HR'],
    'Salary': [50000, 70000, None, 45000, 52000],
    'YearsAtCompany': [5, None, 8, 3, 4]
}
```

In [20]:
import pandas as pd

employee_data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['John', 'Emily', 'Sara', 'Tom', 'Anna'],
    'Department': ['HR', 'IT', 'Marketing', None, 'HR'],
    'Salary': [50000, 70000, None, 45000, 52000],
    'YearsAtCompany': [5, None, 8, 3, 4]
}

df = pd.DataFrame(employee_data)

df['Salary'].fillna(df['Salary'].mean(), inplace=True)
df['YearsAtCompany'].fillna(df['YearsAtCompany'].mean(), inplace=True)

df

/var/folders/51/k_yn4qxs0_nfrm1hk39_0m2r0000gn/T/ipykernel_20352/1892410554.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
/var/folders/51/k_yn4qxs0_nfrm1hk39_0m2r0000gn/T/ipykernel_20352/1892410554.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['YearsAtCompany'].fillna(df['YearsAtCompany'].mean(), inplace=True)

   EmployeeID   Name Department   Salary  YearsAtCompany
0         101   John         HR  50000.0             5.0
1         102  Emily         IT  70000.0             5.0
2         103   Sara  Marketing  54250.0             8.0
3         104    Tom       None  45000.0             3.0
4         105   Anna         HR  52000.0             4.0

### [실습 2] **중복값 제거**

다음은 한 판매점의 제품 판매 기록입니다. 동일한 제품이 중복으로 기록되어 있습니다. 중복된 `ProductID`를 가진 제품의 중복된 행을 제거한 후, 가장 저렴한 가격을 가진 데이터만 남기세요.

```python
product_data = {
    'ProductID': [1, 2, 3, 1, 4, 2],
    'ProductName': ['Laptop', 'Mouse', 'Monitor', 'Laptop', 'Keyboard', 'Mouse'],
    'Price': [1200, 25, 300, 1150, 45, 22],
    'QuantitySold': [10, 100, 50, 8, 70, 120]
}
```

In [21]:
import pandas as pd

product_data = {
    'ProductID': [1, 2, 3, 1, 4, 2],
    'ProductName': ['Laptop', 'Mouse', 'Monitor', 'Laptop', 'Keyboard', 'Mouse'],
    'Price': [1200, 25, 300, 1150, 45, 22],
    'QuantitySold': [10, 100, 50, 8, 70, 120]
}

df = pd.DataFrame(product_data)

# 1. 가격(Price)을 기준으로 오름차순 정렬
# (이렇게 하면 같은 ProductID 중에서 가격이 낮은 항목이 리스트의 위쪽으로 오게 됩니다)
df_sorted = df.sort_values(by='Price', ascending=True)

# 2. ProductID를 기준으로 중복 제거
# keep='first' 옵션은 중복된 값 중 가장 위에 있는 첫 번째 값(아까 정렬한 최저가 항목)을 남깁니다.
df_result = df_sorted.drop_duplicates(subset='ProductID', keep='first')

# 3. 인덱스 재설정 (깔끔한 출력을 위해 기존 인덱스를 버리고 새로 매깁니다)
df_result = df_result.reset_index(drop=True)

# 결과 확인
print(df_result)

   ProductID ProductName  Price  QuantitySold
0          2       Mouse     22           120
1          4    Keyboard     45            70
2          3     Monitor    300            50
3          1      Laptop   1150             8

### [실습 3] **데이터 정렬**

다음은 자동차 모델별 성능 데이터를 포함하고 있습니다. `마력(horsepower)`을 기준으로 오름차순으로 데이터를 정렬한 후, `연비(mpg)`가 높은 상위 3개 자동차만 출력하세요.

```python
car_data = {
    'Model': ['Sedan', 'SUV', 'Truck', 'Coupe', 'Convertible'],
    'Horsepower': [180, 250, 200, 170, 150],
    'MPG': [30, 20, 15, 35, 28],
    'Price': [30000, 45000, 40000, 28000, 32000]
}
```

In [33]:
car_data = {
    'Model': ['Sedan', 'SUV', 'Truck', 'Coupe', 'Convertible'],
    'Horsepower': [180, 250, 200, 170, 150],
    'MPG': [30, 20, 15, 35, 28],
    'Price': [30000, 45000, 40000, 28000, 32000]
}

df = pd.DataFrame(car_data)
df_sorted = df.sort_values(by='Horsepower').nlargest(3, 'MPG')
print(df_sorted)

         Model  Horsepower  MPG  Price
3        Coupe         170   35  28000
0        Sedan         180   30  30000
4  Convertible         150   28  32000

### [실습 4] **데이터 필터링**

다음은 축구 선수들의 데이터를 나타냅니다. 필터링을 통해 포지션이 "Forward"이고, 나이가 30 이하인 선수만 출력하세요.

```python
football_data = {
    'PlayerID': [201, 202, 203, 204, 205],
    'Name': ['Ronaldo', 'Messi', 'Neymar', 'Mbappe', 'Kane'],
    'Position': ['Forward', 'Forward', 'Midfielder', 'Forward', 'Forward'],
    'GoalsScored': [600, 700, 400, 150, 200],
    'Age': [35, 33, 29, 22, 27]
}
```

In [38]:
import pandas as pd

football_data = {
    'PlayerID': [201, 202, 203, 204, 205],
    'Name': ['Ronaldo', 'Messi', 'Neymar', 'Mbappe', 'Kane'],
    'Position': ['Forward', 'Forward', 'Midfielder', 'Forward', 'Forward'],
    'GoalsScored': [600, 700, 400, 150, 200],
    'Age': [35, 33, 29, 22, 27]
}

# DataFrame 생성
df = pd.DataFrame(football_data)

# 데이터 필터링 조건 설정
# 1. Position 컬럼의 값이 'Forward' 인 경우
# 2. Age 컬럼의 값이 30 이하(<=) 인 경우
# 두 조건을 모두 만족해야 하므로 AND 연산자(&)를 사용합니다.
# (Pandas 조건문에서는 괄호로 각 조건을 묶어주는 것이 중요합니다)
filtered_result = df[ (df['Position'] == 'Forward') & (df['Age'] <= 30) ]

# 결과 출력
print(filtered_result)

   PlayerID    Name Position  GoalsScored  Age
3       204  Mbappe  Forward          150   22
4       205    Kane  Forward          200   27

## **[종합 실습 1] 상품 판매 데이터 분석**

다음은 한 전자상거래 사이트의 **상품 판매 데이터**입니다. 고객들이 특정 상품을 구매한 기록이 포함되어 있습니다. 데이터를 활용하여 아래의 문제를 해결하세요.

In [75]:
import pandas as pd

# 예시 상품 판매 데이터
sales_data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product': ['Laptop', 'Mouse', 'Laptop', 'Monitor', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Monitor', 'Keyboard'],
    'Quantity': [1, 2, 1, 1, 2, 1, 1, 3, 1, 1],
    'Price': [1200, 25, 1200, 300, 25, 100, 1200, 25, 300, 100],
    'CustomerID': [1001, 1002, 1001, 1003, 1004, 1002, 1001, 1003, 1005, 1002],
    'OrderDate': ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-10', '2024-01-12', '2024-01-15', '2024-01-18', '2024-01-20', '2024-01-22', '2024-01-25']
}
df_sales = pd.DataFrame(sales_data)

   OrderID   Product  Quantity  Price  CustomerID   OrderDate
0      101    Laptop         1   1200        1001  2024-01-05
1      102     Mouse         2     25        1002  2024-01-06
2      103    Laptop         1   1200        1001  2024-01-07
3      104   Monitor         1    300        1003  2024-01-10
4      105     Mouse         2     25        1004  2024-01-12
5      106  Keyboard         1    100        1002  2024-01-15
6      107    Laptop         1   1200        1001  2024-01-18
7      108     Mouse         3     25        1003  2024-01-20
8      109   Monitor         1    300        1005  2024-01-22
9      110  Keyboard         1    100        1002  2024-01-25

1. 각 고객(`CustomerID`)별로 총 구매 금액을 계산하세요.
2. `Laptop`을 구매한 고객들의 평균 구매 금액을 계산하세요.
3. 가장 많이 판매된 상품(상품 이름과 판매된 총 수량)을 구하세요.
4. `OrderDate`가 2024년 1월 10일 이후인 주문만 필터링하여 출력하세요.
5. `Product`별로 판매량과 총 판매 금액을 계산한 후, 이를 `Price` 기준으로 내림차순으로 정렬하여 출력하세요.

In [87]:
import pandas as pd
# 데이터
sales_data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product': ['Laptop', 'Mouse', 'Laptop', 'Monitor', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Monitor', 'Keyboard'],
    'Quantity': [1, 2, 1, 1, 2, 1, 1, 3, 1, 1],
    'Price': [1200, 25, 1200, 300, 25, 100, 1200, 25, 300, 100],
    'CustomerID': [1001, 1002, 1001, 1003, 1004, 1002, 1001, 1003, 1005, 1002],
    'OrderDate': ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-10', '2024-01-12', '2024-01-15', '2024-01-18', '2024-01-20', '2024-01-22', '2024-01-25']
}

# DataFrame 생성
df_sales = pd.DataFrame(sales_data)

# 'OrderDate'를 날짜 형식으로 변환 (문자열 -> datetime)
df_sales['OrderDate'] = pd.to_datetime(df_sales['OrderDate'])

In [92]:
# 1. 각 고객(CustomerID)별로 총 구매 금액을 계산하세요.
df_sales['TotalAmount'] = df_sales['Price'] * df_sales['Quantity']
customer_total = df_sales.groupby('CustomerID')['TotalAmount'].sum()

customer_total

CustomerID
1001    3600
1002     250
1003     375
1004      50
1005     300
Name: TotalAmount, dtype: int64

In [93]:
# 단계 1: 각 주문 건별 '총 금액(TotalAmount)' 계산
# (개별 단가 Price * 수량 Quantity)을 곱해서 새로운 컬럼으로 만듭니다.
df_sales['TotalAmount'] = df_sales['Price'] * df_sales['Quantity']

# 단계 2: 고객별(CustomerID)로 그룹화(groupby)하여 총 금액의 합(sum) 집계
customer_total = df_sales.groupby('CustomerID')['TotalAmount'].sum()

# 단계 3: 보기 좋게 결과 인덱스 리셋 (선택 사항)
customer_total_df = customer_total.reset_index()

print("== 고객별 총 구매 금액 ==")
print(customer_total_df)

== 고객별 총 구매 금액 ==
   CustomerID  TotalAmount
0        1001         3600
1        1002          250
2        1003          375
3        1004           50
4        1005          300

In [81]:
# ------------------------------------------------------------------------------------------------
# 2. `Laptop`을 구매한 고객들의 평균 구매 금액을 계산하세요.
# ------------------------------------------------------------------------------------------------

# 단계 1: 'Laptop'을 구매한 데이터만 필터링
laptop_sales = df_sales[df_sales['Product'] == 'Laptop']

# 단계 2: Laptop 구매 고객 집단의 'TotalAmount' 평균 계산
laptop_avg_amount = laptop_sales['TotalAmount'].mean()

print(f"\n== Laptop 구매 고객 평균 구매액: {laptop_avg_amount:.2f} ==")

== Laptop 구매 고객 평균 구매액: 1200.00 ==

In [82]:
# ------------------------------------------------------------------------------------------------
# 3. 가장 많이 판매된 상품(상품 이름과 판매된 총 수량)을 구하세요.
# ------------------------------------------------------------------------------------------------

# 단계 1: 상품별(Product) 판매 수량(Quantity) 합계 계산
product_quantity = df_sales.groupby('Product')['Quantity'].sum()

# 단계 2: 판매 수량이 가장 많은(max) 상품 찾기 - idxmax() 사용 (인덱스 반환)
top_product_name = product_quantity.idxmax()
top_product_qty = product_quantity.max()

print(f"\n== 가장 많이 판매된 상품: {top_product_name} ({top_product_qty}개) ==")

== 가장 많이 판매된 상품: Mouse (7개) ==

In [83]:
# ------------------------------------------------------------------------------------------------
# 4. `OrderDate`가 2024년 1월 10일 이후인 주문만 필터링하여 출력하세요.
# ------------------------------------------------------------------------------------------------

# 단계 1: 날짜 조건 필터링 (> '2024-01-10')
recent_orders = df_sales[df_sales['OrderDate'] > '2024-01-10']

print("\n== 2024년 1월 10일 이후 주문 ==")
print(recent_orders)

== 2024년 1월 10일 이후 주문 ==
   OrderID   Product  Quantity  Price  CustomerID  OrderDate  TotalAmount
4      105     Mouse         2     25        1004 2024-01-12           50
5      106  Keyboard         1    100        1002 2024-01-15          100
6      107    Laptop         1   1200        1001 2024-01-18         1200
7      108     Mouse         3     25        1003 2024-01-20           75
8      109   Monitor         1    300        1005 2024-01-22          300
9      110  Keyboard         1    100        1002 2024-01-25          100

In [84]:
# ------------------------------------------------------------------------------------------------
# 5. `Product`별로 판매량과 총 판매 금액을 계산한 후, 이를 `Price` 기준으로 내림차순으로 정렬하여 출력하세요.
# ------------------------------------------------------------------------------------------------

# 단계 1: 상품별(Product)로 그룹화하여 -> 수량(Quantity)과 총금액(TotalAmount) 합계 집계
product_stats = df_sales.groupby('Product')[['Quantity', 'TotalAmount']].sum()

# 단계 2: 'TotalAmount' 기준으로 내림차순(descending) 정렬
# (문제에서는 Price 기준이라고 했으나, 집계된 데이터 프레임에는 Price 컬럼이 없고 TotalAmount가 더 적절할 수 있음. 
# 하지만 문제 의도가 '집계 후 총 판매금액 순'이라면 TotalAmount 사용, 만약 '단가'라면 원본 정보 병합 필요.
# 여기서는 '총 판매 금액'을 기준으로 정렬하겠습니다.)
product_stats_sorted = product_stats.sort_values(by='TotalAmount', ascending=False)

print("\n== 상품별 판매량 및 총 판매 금액 (매출액 순 정렬) ==")
print(product_stats_sorted)

== 상품별 판매량 및 총 판매 금액 (매출액 순 정렬) ==
          Quantity  TotalAmount
Product
Laptop           3         3600
Monitor          2          600
Keyboard         2          200
Mouse            7          175

## [종합 실습 2] **컨텐츠 선호 데이터 분석**

다음은 사용자가 다양한 컨텐츠를 평가한 **컨텐츠 선호 데이터**입니다. 사용자가 영화, 음악, 책 등을 평가한 데이터를 바탕으로 분석을 수행하세요.

```python
import pandas as pd

# 예시 컨텐츠 선호 데이터
preference_data = {
    'UserID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'ContentID': [101, 102, 101, 103, 104, 105, 106, 101, 107, 102],
    'ContentType': ['Movie', 'Music', 'Movie', 'Book', 'Movie', 'Music', 'Book', 'Movie', 'Music', 'Book'],
    'Rating': [5, 3, 4, 2, 5, 4, 3, 4, 5, 2],
    'ReviewDate': ['2024-02-01', '2024-02-02', '2024-02-03', '2024-02-05', '2024-02-07', '2024-02-10', '2024-02-12', '2024-02-14', '2024-02-15', '2024-02-20']
}
df_preference = pd.DataFrame(preference_data)
```

1. 각 컨텐츠 타입(`ContentType`)별로 평균 평점을 계산하세요.
2. 가장 높은 평점을 받은 `ContentID`와 해당 평점을 구하세요.
3. 
4. `ReviewDate`가 2024년 2월 10일 이후인 리뷰 중에서 `Rating`이 4 이상인 데이터를 필터링하여 출력하세요.
5. 각 사용자(`UserID`)가 평가한 컨텐츠 수를 계산하고, 이를 출력하세요.

In [95]:
import pandas as pd

# 예시 컨텐츠 선호 데이터
preference_data = {
    'UserID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'ContentID': [101, 102, 101, 103, 104, 105, 106, 101, 107, 102],
    'ContentType': ['Movie', 'Music', 'Movie', 'Book', 'Movie', 'Music', 'Book', 'Movie', 'Music', 'Book'],
    'Rating': [5, 3, 4, 2, 5, 4, 3, 4, 5, 2],
    'ReviewDate': ['2024-02-01', '2024-02-02', '2024-02-03', '2024-02-05', '2024-02-07', '2024-02-10', '2024-02-12', '2024-02-14', '2024-02-15', '2024-02-20']
}
df_preference = pd.DataFrame(preference_data)
df_preference

   UserID  ContentID ContentType  Rating  ReviewDate
0       1        101       Movie       5  2024-02-01
1       2        102       Music       3  2024-02-02
2       3        101       Movie       4  2024-02-03
3       4        103        Book       2  2024-02-05
4       5        104       Movie       5  2024-02-07
5       6        105       Music       4  2024-02-10
6       7        106        Book       3  2024-02-12
7       8        101       Movie       4  2024-02-14
8       9        107       Music       5  2024-02-15
9      10        102        Book       2  2024-02-20

In [97]:
# contenttype 별 평균평점
df = df_preference.groupby('ContentType')['Rating'].mean()
df

ContentType
Book     2.333333
Movie    4.500000
Music    4.000000
Name: Rating, dtype: float64

In [110]:
# 가장 높은 평점을 받은 content_ID와 해당 평점
df_preference
df = df_preference.sort_values(by='Rating').idxmax()
df

UserID         9
ContentID      8
ContentType    1
Rating         0
ReviewDate     9
dtype: int64

In [118]:
# Movie 유형 컨텐츠에 대해 평점이 4 이상인 사용자들의 데이터
# df_preference

df_movie_rating = df_preference[(df_preference['ContentType'] == 'Movie') & (df_preference['Rating'] >= 4)]
df_movie_rating

   UserID  ContentID ContentType  Rating  ReviewDate
0       1        101       Movie       5  2024-02-01
2       3        101       Movie       4  2024-02-03
4       5        104       Movie       5  2024-02-07
7       8        101       Movie       4  2024-02-14

In [119]:
# ReviewDate가 2024년 2월 10일 이후인 리뷰 중에서 Rating이 4 이상인 데이터
df_preference['ReviewDate'] = pd.to_datetime(df_preference['ReviewDate'])
df_review = df_preference[
    ((df_preference['ReviewDate'] >= '2024-02-10') & (df_preference['Rating'] >= 4))
]
df_review

   UserID  ContentID ContentType  Rating ReviewDate
5       6        105       Music       4 2024-02-10
7       8        101       Movie       4 2024-02-14
8       9        107       Music       5 2024-02-15

In [120]:
df_preference
# 각 컨텐츠별 평가한 유저 수 계산해서 출력

   UserID  ContentID ContentType  Rating ReviewDate
0       1        101       Movie       5 2024-02-01
1       2        102       Music       3 2024-02-02
2       3        101       Movie       4 2024-02-03
3       4        103        Book       2 2024-02-05
4       5        104       Movie       5 2024-02-07
5       6        105       Music       4 2024-02-10
6       7        106        Book       3 2024-02-12
7       8        101       Movie       4 2024-02-14
8       9        107       Music       5 2024-02-15
9      10        102        Book       2 2024-02-20