In [6]:
import pandas as pd

# 예시 상품 판매 데이터
sales_data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product': ['Laptop', 'Mouse', 'Laptop', 'Monitor', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Monitor', 'Keyboard'],
    'Quantity': [1, 2, 1, 1, 2, 1, 1, 3, 1, 1],
    'Price': [1200, 25, 1200, 300, 25, 100, 1200, 25, 300, 100],
    'CustomerID': [1001, 1002, 1001, 1003, 1004, 1002, 1001, 1003, 1005, 1002],
    'OrderDate': ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-10', '2024-01-12', '2024-01-15', '2024-01-18', '2024-01-20', '2024-01-22', '2024-01-25']
}
df_sales = pd.DataFrame(sales_data)
df_sales

   OrderID   Product  Quantity  Price  CustomerID   OrderDate
0      101    Laptop         1   1200        1001  2024-01-05
1      102     Mouse         2     25        1002  2024-01-06
2      103    Laptop         1   1200        1001  2024-01-07
3      104   Monitor         1    300        1003  2024-01-10
4      105     Mouse         2     25        1004  2024-01-12
5      106  Keyboard         1    100        1002  2024-01-15
6      107    Laptop         1   1200        1001  2024-01-18
7      108     Mouse         3     25        1003  2024-01-20
8      109   Monitor         1    300        1005  2024-01-22
9      110  Keyboard         1    100        1002  2024-01-25

# 1번

In [7]:
# 총 구매금액으로 새로운 컬럼 만들기
df_sales['Total'] = df_sales['Quantity'] * df_sales['Price']

# 고객별 총 구매금액 계산하기
customer_total = df_sales.groupby('CustomerID')['Total'].sum()

# 결과 출력
customer_total

CustomerID
1001    3600
1002     250
1003     375
1004      50
1005     300
Name: Total, dtype: int64

# 2번 - Laptop을 구매한 고객들의 평균 구매 금액

In [10]:
# 1. 랩탑 구매자 데이터 구하기
laptop_sales = df_sales[df_sales['Product'] == 'Laptop']
# laptop_sales

# 2. 랩탑 구매자의 총 구매금액의 평균
laptop_avg_purchase = laptop_sales['Total'].mean()
laptop_avg_purchase

np.float64(1200.0)

# 3번 - 가장 많이판매된 상품의 이름과 판매된 총 수량

In [13]:
# 상품별 판매수량 합계 계산 (groupby 사용 reset_index 사용 안함)
product_sales = df_sales.groupby('Product')['Quantity'].sum()
# product_sales
# idxmax(): 가장 큰 값을 가진 인덱스 반환 / max(): 가장 큰 값을 반환
best_product = product_sales.idxmax()
best_product_qt = product_sales.max()
print(f"가장 많이 판매된 상품: {best_product} ({best_product_qt}개)")

가장 많이 판매된 상품: Mouse (7개)

# 4번 - OrderDate가 2024년 1월 10일 이후인 주문만 필터링하여 출력

In [17]:
df_sales
# 1. 대소비교를 위해 OrderDate 컬럼의 값을 datetime 형식으로 반환받음
df_sales['OrderDate'] = pd.to_datetime(df_sales['OrderDate'])
# df_sales.info()

# 2 OrderDate > '2024-01-10'인 데이터 출력
filtered_sales = df_sales[df_sales['OrderDate'] > '2024-01-10']
filtered_sales

   OrderID   Product  Quantity  Price  CustomerID  OrderDate  Total
4      105     Mouse         2     25        1004 2024-01-12     50
5      106  Keyboard         1    100        1002 2024-01-15    100
6      107    Laptop         1   1200        1001 2024-01-18   1200
7      108     Mouse         3     25        1003 2024-01-20     75
8      109   Monitor         1    300        1005 2024-01-22    300
9      110  Keyboard         1    100        1002 2024-01-25    100

# 5번 - Product별 판매량과 총 판매 금액을 계산한 후, 이를 총. ㅏㄴ매금액 기준으로 내림차순으로 정렬

In [19]:
# 상품별 판매량과 총 판매금액(agg함수 사용)
product_stats = df_sales.groupby('Product').agg({'Quantity': 'sum', 'Total': 'sum'})
product_stats

# 총 판매금액 기준으로 내림차순 정렬
sorted_stats = product_stats.sort_values(by='Total', ascending=False)
sorted_stats

          Quantity  Total
Product
Laptop           3   3600
Monitor          2    600
Keyboard         2    200
Mouse            7    175

# 종합실습 2

1. 각 컨텐츠 타입(`ContentType`)별로 평균 평점을 계산하세요.
2. 가장 높은 평점을 받은 `ContentID`와 해당 평점을 구하세요.
3. `Movie` 유형 컨텐츠에 대해 평점이 4 이상인 사용자들의 데이터를 필터링하세요.
4. `ReviewDate`가 2024년 2월 10일 이후인 리뷰 중에서 `Rating`이 4 이상인 데이터를 필터링하여 출력하세요.
5. 각 컨텐츠별(`ContentID`) 평가한  유저수를 계산하고, 이를 출력하세요.

In [31]:
import pandas as pd

# 예시 컨텐츠 선호 데이터
preference_data = {
    'UserID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'ContentID': [101, 102, 101, 103, 104, 105, 106, 101, 107, 102],
    'ContentType': ['Movie', 'Music', 'Movie', 'Book', 'Movie', 'Music', 'Book', 'Movie', 'Music', 'Book'],
    'Rating': [5, 3, 4, 2, 5, 4, 3, 4, 5, 2],
    'ReviewDate': ['2024-02-01', '2024-02-02', '2024-02-03', '2024-02-05', '2024-02-07', '2024-02-10', '2024-02-12', '2024-02-14', '2024-02-15', '2024-02-20']
}
df_preference = pd.DataFrame(preference_data)

In [23]:
# 1.
content_avg_rating = df_preference.groupby('ContentID').agg({'Rating': 'mean'})

In [29]:
# 2.
# 가장 높은 평점을 받은 컨텐츠 데이터
max_rating_content = df_preference.loc[df_preference['Rating'].idxmax()]
print(max_rating_content)
print("================")
# 그 컨텐츠의 ContentID
print(max_rating_content['ContentID'])

UserID                  1
ContentID             101
ContentType         Movie
Rating                  5
ReviewDate     2024-02-01
Name: 0, dtype: object
================
101

In [34]:
# 3. df_preference[(조건) & 조건] 형태
movie_high_rating = df_preference[(df_preference['ContentType'] == 'Movie') & (df_preference ['Rating'] >= 4)]
movie_high_rating

   UserID  ContentID ContentType  Rating  ReviewDate
0       1        101       Movie       5  2024-02-01
2       3        101       Movie       4  2024-02-03
4       5        104       Movie       5  2024-02-07
7       8        101       Movie       4  2024-02-14

In [ ]:
# 4. 날짜 대소비교를 위해 ReviewDate 컬럼을 datetime으로 변환
df_preference['ReviewDate'] = pd.to_datetime(df_preference['ReviewDate'])

# df_preference[(조건1) & (조건2)] 형태
filtered_reviews = df_preference[(df_preference['ReviewDate'] >= '2022-01-01') & (df_preference['ReviewDate'] <= '2022-12-31')]

In [35]:
# 5
content_count = df_preference.groupby('ContentID')['UserID'].count()
content_count

ContentID
101    3
102    2
103    1
104    1
105    1
106    1
107    1
Name: UserID, dtype: int64